---

#########################################################
## Auto Update                                         ##
#########################################################

# Debug messg
- name: Show message
  ansible.builtin.debug:
    msg: "Install auto update packages, this may take a while..."

# Install cockpit packages
- name: Install auto update package
  ansible.builtin.package:
    name:
      - dnf-automatic
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

# Install cockpit packages on Ubuntu
- name: Install auto update package
  ansible.builtin.package:
    name:
      - unattended-upgrades
    state: present
  when: ansible_distribution == "Ubuntu"

# Enable auto update service on rhel
# https://access.redhat.com/solutions/2823901
- name: Restart auto update service
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: dnf-automatic-install.timer
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

# Enable auto update service on ubuntu
- name: Restart auto update service
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: unattended-upgrades.service
  when: ansible_distribution == "Ubuntu"
