---

#########################################################
## Installation                                        ##
#########################################################

# Debug messg
- name: Show message
  ansible.builtin.debug:
    msg: "Install auto update packages, this may take a while..."

# Install cockpit packages
- name: Install auto update package
  ansible.builtin.package:
    name:
      - dnf-automatic
    state: present

# Enable auto update service
# https://access.redhat.com/solutions/2823901
- name: Restart auto update service
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: dnf-automatic-install.timer
