---
# This is the main installation file to install the lab core services server
# It will install the following:
# - podman, cockpit, hashicorp vault, nexus repository

- name: Install Lab Playground server
  hosts: lab_core_services
  become: true
  vars:
    # if uninstall is true, roles will be uninstalled first before installation.
    uninstall: false
    automation_username: "ansible"
    # automation_password: "" # Will be generated and stored in Vault
    automation_email: "ansible@me.local"

    vm_name: "LABCS"

  roles:

  tasks:
    # Information message
    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "#########################################################"
          - "Install Lab Core Services"
          - "#########################################################"
          - "#########################################################"

    # Information message
    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "First server configuration"
          - "#########################################################"

    # Configure server
    - name: Configure server first install...
      ansible.builtin.include_role:
        name: server-config
      vars:
        action: "first_config"
        server_hostname: "{{ vm_name }}.development.local"

    # Register global variable
    - name: Register global variable (server_hostname)...
      ansible.builtin.set_fact:
        server_hostname: "{{ server_hostname }}"
      delegate_to: localhost

    # Install podman container engine
    - name: Install Podman container engine...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: "install"

    # Install cockpit management gui
    - name: Install Cockpit management gui...
      ansible.builtin.include_role:
        name: cockpit
      vars:
        action: "install"
        cockpit_branding_logo: "./media/banner_lab.png"

    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "Install Hashicorp Vault secrets management"
          - "#########################################################"

    # Install Hashicorp Vault
    - name: Install Hashicorp Vault secret management...
      ansible.builtin.include_role:
        name: vault
      vars:
        action: "install"
        vault_repository_url: "docker.io/hashicorp/vault"

    # Add server config to vault
    - name: Configure vault
      ansible.builtin.include_role:
        name: server-config
      vars:
        action: "configure_vault"
        # automation_username: # set in playbook variables.
        # automation_password: # set in playbook variables.
        # automation_email:    # set in playbook variables.

    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "Install Nexus Repository artifacts management"
          - "#########################################################"

    # Install Nexus Repository
    - name: Setup Nexus Repository role and modules...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "install"
        nexus_repository_url     : "docker.io/sonatype/nexus3"
        nexus_repository_vault_id: "{{ server_hostname }}"
        # automation_username    : "" # defined at playbook level
        # automation_password    : "" # defined at playbook level
        # automation_email       : "" # defined at playbook level

    # Create repository
    - name: Create repository (files)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        # nexus_repository_address : "" # defined at playbook level
        # nexus_repository_username: "" # defined at playbook level
        # nexus_repository_password: "" # defined at playbook level
        nexus_repository_vault_id  : "{{ server_hostname }}"
        nexus_repository_name      : "files"
        nexus_repository_type      : "raw"

    # Create repository
    - name: Create repository (os_templates)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        # nexus_repository_address : "" # defined at playbook level
        # nexus_repository_username: "" # defined at playbook level
        # nexus_repository_password: "" # defined at playbook level
        nexus_repository_vault_id  : "{{ server_hostname }}"
        nexus_repository_name      : "os_templates"
        nexus_repository_type      : "raw"

    # Create repository
    - name: Create repository (operating_systems)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        # nexus_repository_address : "" # defined at playbook level
        # nexus_repository_username: "" # defined at playbook level
        # nexus_repository_password: "" # defined at playbook level
        nexus_repository_vault_id  : "{{ server_hostname }}"
        nexus_repository_name      : "operating_systems"
        nexus_repository_type      : "raw"

    # Create repository
    - name: Create repository (containers)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        # nexus_repository_address : "" # defined at playbook level
        # nexus_repository_username: "" # defined at playbook level
        # nexus_repository_password: "" # defined at playbook level
        nexus_repository_vault_id  : "{{ server_hostname }}"
        nexus_repository_name      : "containers"
        nexus_repository_type      : "docker"


    # Information message
    - name: Show information message
      debug:
        msg:
          - "Installation of Playground Lab Core Services completed..."
          - "Server: {{ server_hostname }}."
          - "Vault address: {{ vault_address }} - Vault token: {{ vault_token }}"
          - "Nexus repository: {{ nexus_repository_address }}."
          - "Nexus admin password stored in Vault."
          - "Nexus repositories created: files, os_templates, operating_systems."
