---
# This is the main installation file to install the lab server
# It will install the following:
# - podman, cockpit, hashicorp vault, semaphore, gogs, nexus repository
#
#

- name: Install Lab Playground server
  hosts: lab_server
  vars:
    # if uninstall is true, roles will be uninstalled first before installation.
    uninstall: true
    automation_username: ansible
    automation_email: "ansible@marcelvenema.com"
    lab_username: "admin"
    lab_password: "Password29!"
    lab_email: "marcel@marcelvenema.com"

  roles:
    - role: server_config_linux
      become: true
      vars:
        action: configure_playground
        admin_hostname: "lab.marcelvenema.com"
        admin_username: "{{ lab_username }}"
        admin_usercomment: "Admin user for lab server"
        admin_password: "{{ lab_password }}"
        admin_email: "{{ lab_email }}"

    - role: podman
      become: true
      gather_facts: true
      vars:
        action: install

    - role: cockpit
      become: true
      gather_facts: true  
      vars:
        action: install

    - role: vault
      become: true
      vars:
        action: install
        # repository url can be a url to repository or a local file. example: docker.io/hashicorp/vault or /tmp/vault_<version>.tar
        repository_url: "docker.io/hashicorp/vault"
        # repository_url: "/repository/vault_1.15.0.tar"
        # repository_tag can be a tag or a version. example: 1.15.0 or 1.15.0-beta1. default is 'latest'.
        # repository_tag: 1.14.8
        # data_dir : base folder to store data. example: "/data/vault" # default is /data/vault
        data_dir: "/data/vault"

    - role: server_config_linux
      become: true
      gather_facts: true
      vars:
        action: configure_vault
        admin_username: "{{ lab_username }}"
        admin_password: "{{ lab_password }}"
        admin_email: "{{ lab_email }}"
        # vault_address: <address>, example: https://localhost:8200 not neccecary if vault is installed on the same server
        # vault_token: <token>, not neccecary if vault is installed on the same server

    - role: mysql
      become: true
      vars:
        action: install
        # repository url can be a url to repository or a local file. example: docker.io/mysql/mysql-server or /tmp/mysql_<version>.tar
        # repository_url: "docker.io/mysql/mysql-server"
        repository_url: "/repository/mysql_8.1.0.tar"
        # repository_tag: "latest"
        # vault_address: <address>, example: https://localhost:8200 not neccecary if vault is installed on the same server
        # vault_token: <token>, not neccecary if vault is installed on the same server

    - role: semaphore
      become: true
      vars:
        action: install
        # repository_url: "docker.io/semaphoreui/semaphore"
        repository_url: "/repository/semaphore_v2.9.37.tar"
        semaphore_admin_username: "{{ lab_username }}"
        semaphore_admin_password: "{{ lab_password }}"
        semaphore_admin_email: "{{ lab_email }}"
        # vault_address: <address>, example: https://localhost:8200 not neccecary if vault is installed on the same server
        # vault_token: <token>, not neccecary if vault is installed on the same server

    - role: gogs
      become: true
      vars:
        action: install
        # repository_url: "docker.io/gogs/gogs"
        repository_url: "/repository/gogs_0.13.tar"
        # vault_address: <address>, example: https://localhost:8200 not neccecary if vault is installed on the same server
        # vault_token: <token>, not neccecary if vault is installed on the same server

    - role: nexus_repository
      become: true
      vars:
        action: install
        # repository url can be a url to repository or a local file. example: docker.io/sonatype/nexus3 or /tmp/nexus_<version>.tar
        # repository_url: "docker.io/sonatype/nexus3"
        repository_url: "/repository/nexus_3.61.0.tar"
        # vault_address: <address>, example: https://localhost:8200 not neccecary if vault is installed on the same server
        # vault_token: <token>, not neccecary if vault is installed on the same server
                                        
  tasks:
    - name: Show information message
      debug:
        msg:
          - "Lab server installation completed..."
          - "Cockpit can be accessed at https://{{ admin_hostname }}:9090. Username is {{ lab_username }} and password is {{ lab_password }}."
          - "Hashicorp Vault can be accessed at https://{{ admin_hostname }}:8200. Unseal keys are stored at /data/vault/config/unseal_keys. Root token is stored at /data/vault/config/vault_token. Value: {{ vault_token }}"
          - "Semaphore can be accessed at https://{{ admin_hostname }}:3000 with username {{ lab_username }} and password {{ lab_password }}."
          - "Gogs can be accessed at http://{{ admin_hostname }}:3001"
          - "Sonatype Nexus Repository OSS can be accessed at http://{{ admin_hostname }}:8081"
