---

- name: Install Lab Playground server
  hosts: lab_core_services
  become: true
  vars:
    # if uninstall is true, roles will be uninstalled first before installation.
    uninstall: false
    vm_name: "LABCS"

  tasks:
    # Information message
    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "#########################################################"
          - "Install Lab Core Services"
          - "#########################################################"
          - "#########################################################"

    # Information message
    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "First server configuration"
          - "#########################################################"

    # Test for ansible version, recommended version is 2.18+, show warning if version is lower
    - name: Test for ansible version...
      ansible.builtin.assert:
        that: "ansible_version.full is version('2.18', '>=')"
        fail_msg: "Ansible version is lower than 2.18. Recommended version is 2.18+"
        quiet: true

    # Set server hostname
    - name: "Set server hostname..."
      ansible.builtin.set_fact:
        server_hostname: "{{ vm_name }}.development.local"

    # Set hostname
    - name: "Set hostname to {{ server_hostname }}..."
      become: true
      ansible.builtin.hostname:
        name: "{{ server_hostname }}"
      when: server_hostname is defined

    # Install podman container engine
    - name: Install Podman container engine...
      ansible.builtin.include_role:
        name: podman
      vars:
        action: "install"

    # Install cockpit management gui
    - name: Install Cockpit management gui...
      ansible.builtin.include_role:
        name: cockpit
      vars:
        action: "install"
        cockpit_branding_logo: "./media/banner_lab_white.png"

    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "Install Hashicorp Vault secrets management"
          - "#########################################################"

    # Install Hashicorp Vault
    - name: Install Hashicorp Vault secret management...
      ansible.builtin.include_role:
        name: vault
      vars:
        action: "install"
        vault:
          container:
            repository_url: "docker.io/hashicorp/vault"
            repository_tag: "1.20.2"
          secrets:
            secret_name: "{{ server_hostname }}"

    - name: Information message
      ansible.builtin.debug:
        msg:
          - "#########################################################"
          - "Install Nexus Repository artifacts management"
          - "#########################################################"

    # Install Nexus Repository
    - name: Setup Nexus Repository role and modules...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "install"
        nexus_repository:
          container:
            repository_url: "{{ repository_url }}/containers/nexus3_3.80.0.tar"
          secrets:
            secret_name: "{{ server_hostname }}"

    # Create repository
    - name: Create repository (files)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        nexus_repository_name: "files"
        nexus_repository_type: "raw"
        nexus_repository:
          secrets:
            secret_name: "{{ server_hostname }}"

    # Create repository
    - name: Create repository (os_templates)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        nexus_repository_name: "os_templates"
        nexus_repository_type: "raw"
        nexus_repository:
          secrets:
            secret_name: "{{ server_hostname }}"

    # Create repository
    - name: Create repository (operating_systems)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        nexus_repository_name: "operating_systems"
        nexus_repository_type: "raw"
        nexus_repository:
          secrets:
            secret_name: "{{ server_hostname }}"

    # Create repository
    - name: Create repository (containers)...
      ansible.builtin.include_role:
        name: nexus-repository
      vars:
        action: "create_repository"
        nexus_repository_name: "containers"
        nexus_repository_type: "docker"
        nexus_repository:
          secrets:
            secret_name: "{{ server_hostname }}"

    # Information message
    - name: Show information message
      ansible.builtin.debug:
        msg:
          - "Installation of Playground Lab Core Services completed..."
          - "Server: {{ server_hostname }}."
          - "Vault address: {{ vault_address }} - Vault token: {{ vault_token }}"
          - "Nexus repository: {{ nexus_repository_address }}."
          - "Nexus admin password stored in Vault."
          - "Nexus repositories created: containers, files, os_templates, operating_systems."
