---

- name: Playbook to test development
  hosts: lab_server
  tasks:




  #########################################################
  ## Configuration Vault PKI                             ##
  #########################################################

  # Clear variable, be sure it is not used from a previous run.
  - name: Clear variable vault_name
    ansible.builtin.set_fact:
      vault_name: ""
    no_log: true

  # Clear variable, be sure it is not used from a previous run.
  - name: Clear variable vault_description
    ansible.builtin.set_fact:
      vault_description: ""
    no_log: true

  # Create secret engine
  - name: Create secret engine
    ansible.builtin.include_role:
      name: vault
      tasks_from: secret_engine.yml
    vars:
      action: create_secret_engine
      vault_address: "http://192.168.11.22:8200"
      vault_token: "hvs.5XYaP4XJwdV5FqeJpQalQRXr"
      vault_name: "certificates"
      vault_description: "Certificates secrets store"
      vault_type: "pki"
  
  # Delete secret engine
  - name: Delete secret engine
    ansible.builtin.include_role:
      name: vault
      tasks_from: secret_engine.yml
    vars:
      action: destroy_secret_engine
      vault_address: "http://192.168.11.22:8200"
      vault_token: "hvs.5XYaP4XJwdV5FqeJpQalQRXr"
      vault_name: "lab-marcelvenema-com"
      vault_type: "kv"


