---

#########################################################
## Uninstall                                           ##
#########################################################

# Check if data_dir exists, else set default
- name: Check data_dir folder, set default
  ansible.builtin.set_fact:
    data_dir: "/data/gogs"
  when: data_dir is not defined or data_dir == "" or data_dir == none

# Remove Gogs folder
- name: Remove Gogs folder
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: absent

# Remove Gogs pod
- name: Remove gogs git pod
  containers.podman.podman_container:
    name: gogs
    state: absent
