---

#########################################################
## Sonatype Nexus users module                         ##
#########################################################

# Validate global variables
- name: Validate global variables for Sonatype Nexus users module.
  assert:
    that: "{{ varitem }} is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop: 
    - nexus_repository_address
    - nexus_repository_username
    - nexus_repository_password

#########################################################
## Get User                                            ##
#########################################################

- block:

  # Register var_result variable
  - name: Register var_result variable
    set_fact:
      var_result: "{{ var_result }}"
    no_log: true
    when: var_result is not defined

  # Validate local variables
  - name: Validate local variables for Nexus Repository get_user action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - nexus_username

  when : action == "get_user"

#########################################################
## Create User                                         ##
#########################################################

- block:

  # Validate local variables
  - name: Validate local variables for Nexus Repository create_user action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - nexus_firstname
      - nexus_lastname
      - nexus_email
      - nexus_password
      - nexus_roles

  # Create user in Nexus Repository Manager via API
  - name: Create User in Nexus Repository Manager
    uri:
      url: "{{ nexus_repository_address }}/service/rest/v1/security/users"  
      method: POST
      user: "admin"
      password: "{{ nexus_admin_password }}"
      force_basic_auth: yes
      body_format: json 
      body: 
        userId      : "{{ nexus_username }}"
        firstName   : "{{ nexus_firstname }}"
        lastName    : "{{ nexus_lastname }}"
        emailAddress: "{{ nexus_email }}"
        password    : "{{ nexus_password }}"
        status      : "active"
        roles       : ["{{ nexus_roles }}"] 
      headers:
        accept: application/json
        Content-Type: application/json        

  when: action == "create_user"

#########################################################
## Destroy User                                        ##
#########################################################

- block:

  # Validate local variables
  - name: Validate local variables for Nexus Repository destroy_user action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - nexus_username

  # Show information message
  - name: This part is not (yet) implemented.
    debug:
      msg: "This part is not (yet) implemented."

  # Stop playbook
  - name: Stop playbook
    meta: end_play

  when: action == "destroy_user"
