---

#########################################################
## Vault module                                        ##
#########################################################

#########################################################
## Pre-Configuration                                   ##
#########################################################

# Validate variables
- name: Validate variables for action.
  assert:
    that: "{{ item }} is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items: 
    - vault_address
    - vault_token
    - admin_hostname

#########################################################
## Configuration                                       ##
#########################################################

# Clear variable, be sure it is not used from a previous run.
- name: Clear variable vault_name
  set_fact:
    vault_name: ""
  no_log: true

# Clear variable, be sure it is not used from a previous run.
- name: Clear variable vault_description
  set_fact:
    vault_description: ""
  no_log: true

# Create secret engine   
- name: Create secret engine
  include_role: 
    name: vault
    tasks_from: secret_engine.yml
  vars:
    action: create_secret_engine
    vault_name: "{{ ansible_fqdn | replace('.', '-') }}"  
    vault_description: "Secrets for {{ ansible_fqdn }}"

# Store usernames and passwords in Hashicorp Vault.
- name: "Store {{ ansible_fqdn }} usernames and passwords in Vault"
  include_role: 
    name: vault
    tasks_from: secrets.yml
  vars:
    action: create_secret
    vault_name: "{{ ansible_fqdn | replace('.','-')}}"
    secret_name: "{{ ansible_fqdn | replace('.','-')}}"
    secret_keyvalue: "{ 'admin_username': '{{ admin_username }}', 'admin_password': '{{ admin_password }}', 'admin_email': '{{ admin_email }}' }"

