---

#########################################################
## Uninstall                                           ##
#########################################################

# Check if data_dir exists, else set default
- name: Check data_dir folder, set default
  ansible.builtin.set_fact:
    data_dir: "/data/semaphore"
  when: data_dir is not defined or data_dir == "" or data_dir == none

# Remove Semaphore config folder
- name: Remove Semaphore config folder
  ansible.builtin.file:
    path: "{{ data_dir }}/config"
    state: absent

# Remove Semaphore data folder
- name: Remove Semaphore data folder
  ansible.builtin.file:
    path: "{{ data_dir }}/data"
    state: absent

# Remove Semaphore container
- name: Remove Semaphore container
  containers.podman.podman_container:
    name: semaphore
    state: absent
    