---

#########################################################
## Sonatype Nexus update module                        ##
#########################################################

# Validate global variables
- name: Validate global variables for Sonaytype Nexus update module.
  ansible.builtin.assert:
    that: "{{ varitem }} is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop: 
    - repository_url


#########################################################
## Sonatype Nexus update                               ##
#########################################################

- name: Update Nexus repository
  when: action == "update"
  block:

    # Validate local variables
    - name: Validate local variables for Nexus Repository update action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop: 
        - nexus_firstname

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play
  