--- 

#########################################################
## Pre-installation                                    ##
#########################################################

# Gather installed packages
- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

# Check if Podman is installed
- name: Check if Podman container infrastructure is present
  ansible.builtin.debug:
    msg: "Podman is not installed. Please wait while installing Podman prerequisites..."
  when: '"podman" not in ansible_facts.packages'

# Run uninstall if Podman is installed and uninstall is set
- name: Run uninstall playbook if Podman is installed
  ansible.builtin.include_tasks: uninstall.yml
  when: 
    - '"podman" in ansible_facts.packages'
    - uninstall == true

# Install Podman prerequisites
- name: Install Podman prerequisites
  ansible.builtin.package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

#########################################################
## Pre-installation                                    ##
#########################################################

# Install Podman on server
- name: Install Podman on RHEL
  ansible.builtin.package:
    name: podman
    state: present
  when: ansible_os_family == "RedHat"

# install Podman on server  
# TODO error check/test    
- name: Install Podman on Ubuntu
  ansible.builtin.apt:
    name: podman
    update_cache: yes
    state: present
  when: ansible_pkg_mgr == 'apt'

# Start Podman on boot
- name: Start podman on boot
  ansible.builtin.service:
    name: podman
    enabled: yes
    state: started

#########################################################
## Configuration                                       ##
#########################################################

# Configure Podman
- name: Configure
  ansible.builtin.include_tasks: configure.yml

#########################################################
## Post-install                                        ##
#########################################################
