---

#########################################################
## Update                                              ##
#########################################################

- name: Upgrade Podman package
  ansible.builtin.dnf:
    name: "podman"
    state: latest
