---

#########################################################
## Pre-installation                                    ##
#########################################################

# Validate variables
- name: Validate variables for action.
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - repository_url

#########################################################
## Pre-installation platform check                     ##
#########################################################

# Gather installed packages
- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

# Override platform check if platform variable is defined.
- name: Override platform check if platform variable is defined.
  ansible.builtin.set_fact:
    platform_check: false
  when: platform is defined

# Set platform if podman is detected
- name: Set platform if podman is detected
  ansible.builtin.set_fact:
    platform: "podman"
  when:
    - platform_check is not defined
    - '"podman" in ansible_facts.packages'

# Set platform if kubernetes is detected
- name: Set platform if kubernetes is detected
  ansible.builtin.set_fact:
    platform: "kubernetes"
  when:
    - platform_check is not defined
    - '"kubernetes" in ansible_facts.packages'

# Set platform to host if no podman or no kubernetes is detected
- name: Set platform to host if no Podman or Kubernetes is detected
  ansible.builtin.set_fact:
    platform: "host"
  when:
    - platform_check is not defined
    - '"podman" not in ansible_facts.packages'
    - '"kubernetes" not in ansible_facts.packages'

#########################################################
## Pre-installation uninstall                          ##
#########################################################

# Run uninstall if uninstall is set
- name: Run uninstall playbook if set
  ansible.builtin.include_tasks: uninstall.yml
  ignore_errors: true
  when: uninstall == true

#########################################################
## Pre-installation folders                            ##
#########################################################

# Check if data_dir exists, else set default
- name: "Validate data_dir folder {{ data_dir}}..."
  ansible.builtin.set_fact:
    data_dir: "/data/mysql"
  when: 
    - data_dir is not defined or data_dir == "" or data_dir == none

# Create MySQL data folder
- name: "Create MySQL data folder {{ data_dir }}/data"
  ansible.builtin.file:
    path: "{{ data_dir }}/data"
    state: directory
    mode: '0755'

#########################################################
## Pre-installation users/groups                       ##
#########################################################

# Set random password
- name: Set MySQL root password
  ansible.builtin.set_fact:
    mysql_root_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
  no_log: true

#########################################################
## Installation on podman                              ##
#########################################################

- name: Install MySQL on podman
  when: platform == "podman"
  block:

    ##################################
    # Import container image         # 
    ##################################

    # If tag is not defined or empty, set value to latest
    - name: Validate repository_tag, set default
      ansible.builtin.set_fact:
        repository_tag: "latest"
      when:
        - repository_tag is not defined or repository_tag == "" or repository_tag == none

    # Show information message
    - name: Show information message
      ansible.builtin.debug:
        msg: "Download container image from registry, this may take a while..."

    # Pull image from repository to local image repository. If failed, lookup local image file.
    - name: "Pull MySQL container image from repository {{ repository_url}}:{{ repository_tag }}"
      containers.podman.podman_image:
        name: "{{ repository_url }}"
        tag: "{{ repository_tag }}"
      register: pull_result
      ignore_errors: true

    # repository_url is a local container file, check if file exists
    - name: Check if repository_url is a local container file
      ansible.builtin.stat:
        path: "{{ repository_url }}"
      register: repository_url_result
      delegate_to: localhost
      when: pull_result is failed

    # Fail if image file not found
    - name: Fail if MySQL container image file not found
      fail:
        msg: "Repository URL {{ repository_url }} not found. Container image file location not found. Cannot continue..."
      when: 
        - pull_result is failed
        - repository_url_result.stat.exists == false

    # Copy image file to destination
    - name: Copy MySQL container image file to destination
      ansible.builtin.copy:
        src: "{{ repository_url }}"
        dest: "/tmp/mysql.tar"
        mode: '0644'
      when: pull_result is failed

    # Load image from file if pull failed
    - name: Import MySQL container image to podman
      ansible.builtin.command: podman load -i /tmp/mysql.tar
      register: import_result
      when: pull_result is failed

    # Get image info from podman
    - name: Gather info on MySQL container image
      containers.podman.podman_image_info:
        name: mysql-server
      register: image_info_result

    # Get Id from image info
    - name: Get Id from image info
      ansible.builtin.set_fact:
        image_id: "{{ image_info_result.images[0].Id[:12] }}"

    # Cleanup image file
    - name: Cleanup container image file
      ansible.builtin.file:
        path: /tmp/mysql.tar
        state: absent
      when: pull_result is failed

    ##################################
    # Create MySQL container         #
    ##################################

    # Create MySQL pod
    - name: Create MySQL pod
      containers.podman.podman_container:
        name: mysql
        image: "{{ image_id }}"
        ports:
          - 3306:3306
        volumes:
          - /data/mysql/data/:/var/lib/mysql:Z
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"

    # Auto-start MySQL pod on system boot
    - name: Generate systemd unit file for MySQL pod
      containers.podman.podman_generate_systemd:
        name: mysql
        new: true
        no_header: true
        dest: /etc/systemd/system/podman-mysql.service
  
#########################################################
## Installation MySQL on kubernetes                    ##
#########################################################

- name: Install MySQL on kubernetes
  when: platform == "kubernetes"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install MySQL via kubernetes"
  
    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play 

#########################################################
## Installation on host                                ##
#########################################################

- name: Install MySQL on host
  when: platform == "host"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install MySQL on host"

    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play
 
#########################################################
## Configuration                                       ##
#########################################################

# Configure MySQL
- name: Configure MySQL
  ansible.builtin.include_tasks: configure.yml

#########################################################
## Post-install                                        ##
#########################################################

# Unset variables
- name: Unset variables
  ansible.builtin.set_fact:
    repository_tag:
    data_dir:
