---

#########################################################
## Uninstall                                           ##
#########################################################

# Remove Gogs folder
- name: Remove Gogs folder
  file:
    path: /data/gogs
    state: absent

# Remove Gogs pod
- name: Remove gogs git pod
  containers.podman.podman_container:
    name: gogs
    state: absent
