---

#########################################################
## Hashicorp Vault AppRole module                      ##
#########################################################

# Validate global variables
- name: Validate global variables for Hashicorp Vault approles module.
  assert:
    that: "{{ varitem }} is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop: 
    - vault_address
    - vault_token

#########################################################
## Get Vault AppRole                                   ##
#########################################################

- block:

  # Register var_result variable
  - name: Register var_result variable
    set_fact:
      var_result: "{{ var_result }}"
    no_log: true
    when: var_result is not defined

  # Clear variable var_result, be sure it is not used from a previous run.
  - name: Clear variable var_result
    set_fact:
      var_result: ""
    no_log: true

  # Validate local variables
  - name: Validate variables for Vault get_approle action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - vault_policy_name
      - vault_policy_rules

  when: action == "get_approle"


#########################################################
## Create Vault AppRole                                ##
#########################################################

- block:

  # Validate local variables
  - name: Validate variables for Vault reate_approle action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - vault_policy_name
      - vault_policy_rules

  when: action == "create_approle"


#########################################################
## Destroy Vault AppRole                               ##
#########################################################

- block:

  # Validate local variables
  - name: Validate variables for Vault destroy_approle action.
    assert:
      that: "{{ varitem }} is defined"
      fail_msg: "Required variable '{{ varitem }}' has not been provided."
      quiet: true
    loop_control:
      loop_var: varitem
    loop: 
      - vault_policy_name
      - vault_policy_rules

  when: action == "destroy_approle"
