---

#########################################################
## Pre-installation                                    ##
#########################################################

# Validate variables
- name: Validate variables for action.
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items: 
    - repository_url

#########################################################
## Pre-installation platform check                     ##
#########################################################

# Gather installed packages
- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

# Override platform check if platform variable is defined.
- name: Override platform check if platform variable is defined.
  ansible.builtin.set_fact:
    platform_check: false
  when: platform is defined

# Set platform if podman is detected
- name: Set platform if podman is detected
  ansible.builtin.set_fact:
    platform: "podman"
  when:
    - platform_check is not defined
    - '"podman" in ansible_facts.packages'

# Set platform if kubernetes is detected
- name: Set platform if kubernetes is detected
  ansible.builtin.set_fact:
    platform: "kubernetes"
  when:
    - platform_check is not defined
    - '"kubernetes" in ansible_facts.packages'

# Set platform to host if no podman or no kubernetes is detected
- name: Set platform to host if no Podman or Kubernetes is detected
  ansible.builtin.set_fact:
    platform: "host"
  when:
    - platform_check is not defined
    - '"podman" not in ansible_facts.packages'
    - '"kubernetes" not in ansible_facts.packages'

#########################################################
## Pre-installation uninstall                          ##
#########################################################

# Run uninstall if uninstall is set
- name: Run uninstall playbook if set
  ansible.builtin.include_tasks: uninstall.yml
  ignore_errors: true
  when: uninstall == true

#########################################################
## Pre-installation user/group                         ##
#########################################################

# Create Hashicorp Vault user group
- name: Create Hashicorp Vault user group
  ansible.builtin.group: 
    name: "vault"
  become: true

# Create Hashicorp Vault user
- name: Create Hashicorp Vault user
  ansible.builtin.user:
    name: "vault"
    group: "vault"
    system: true
    shell: "/bin/bash"
    comment: "Vault user"
    createhome: "yes"
    state: present

# Enable linger for Hashicorp Vault user
- name: Enable linger for Hashicorp Vault user
  ansible.builtin.command: "loginctl enable-linger vault"

# Create folder for ansible tmp files
- name: Create home folders for user
  ansible.builtin.file:
    path: /home/vault/.ansible/tmp
    state: directory
    owner: vault
    mode: 0700

#########################################################
## Pre-installation folders                            ##
#########################################################

# Check if data_dir exists, else set default
- name: "Validate data_dir folder {{ data_dir}}..."
  ansible.builtin.set_fact:
    data_dir: "/data/vault"
  when: 
    - data_dir is not defined or data_dir == "" or data_dir == none

# Create Hashicorp Vault config folder
- name: "Create Hashicorp Vault folder {{ data_dir }}/config..."
  ansible.builtin.file:
    path: "{{ data_dir }}/config"
    state: directory
    owner: vault
    mode: 0766

# Create Hashicorp Vault storage folder
- name: "Create Hashicorp Vault folder {{ data_dir }}/file..."
  ansible.builtin.file:
    path: "{{ data_dir }}/file"
    state: directory
    owner: vault
    mode: 0766

# Create Hashicorp Vault logs folder
- name: "Create Hashicorp Vault folder {{ data_dir }}/logs..."
  ansible.builtin.file:
    path: "{{ data_dir }}/logs"
    state: directory
    owner: vault
    mode: 0766

#########################################################
## Installation                                        ##
#########################################################

#########################################################
## Installation via podman                             ##
#########################################################

- name: Install Vault on podman
  when: platform == "podman"
  block:
 
    ##################################
    # Import container image         # 
    ##################################

    # If tag is not defined, set value to latest
    - name: Validate repository_tag, set default
      ansible.builtin.set_fact:
        repository_tag: "latest"
      when: repository_tag is not defined or repository_tag == "" or repository_tag == none

    # Show information
    - name: Show information
      ansible.builtin.debug:
        msg: "Get container image from registry. this may take a while..."

    # Pull image from repository to local image repository.
    - name: "Pull Vault container image from repository {{ repository_url}}:{{ repository_tag }}"
      containers.podman.podman_image:
        name: "{{ repository_url }}"
        tag: "{{ repository_tag }}"
      register: pull_result
      ignore_errors: true

    - name: Install local image file
      when: pull_result is failed
      block:

        # repository_url is a local container file, check if file exists on ansible host
        - name: Check if repository_url is a local container file
          ansible.builtin.stat:
            path: "{{ repository_url }}"
          register: repository_url_result
          delegate_to: localhost

        # Fail if image file not found
        - name: Fail if Vault container image file not found
          ansible.builtin.fail:
            msg: "Repository URL {{ repository_url }} not found. Container image file location not found. Cannot continue..."
          when: 
            - repository_url_result.stat.exists == false

        # Copy image file to destination
        - name: Copy Vault container image file to destination
          ansible.builtin.copy:
            src: "{{ repository_url }}"
            dest: "/tmp/vault.tar"

        # Load image from file if pull failed
        - name: Import container image to podman
          ansible.builtin.command: podman load -i /tmp/vault.tar
          register: import_result

        # Cleanup image file
        - name: Cleanup container image file
          ansible.builtin.file:
            path: /tmp/vault.tar
            state: absent

    # Get image info from podman
    - name: Gather info on container image
      containers.podman.podman_image_info:
      register: images_info

    # Find image id
    - name: Parse image info, select container image id
      ansible.builtin.set_fact:
        image_id: "{{ images_info.images | selectattr('RepoTags', 'search', 'vault') | map(attribute='Id') | first }}"

    ##################################
    # Create Vault configuration     #
    ##################################

    # Create Hashicorp Vault configuration
    - name: Create Hashicorp Vault configuration
      ansible.builtin.template:
        src: ./templates/vault.podman_config.hcl.j2
        dest: /data/vault/config/vault.hcl
        owner: vault

    ##################################
    # Create Vault container         #
    ##################################

    # Get uid of user Vault
    - name: Get uid of user Vault
      ansible.builtin.user:
        name: vault
      register: vault_user

    # Set fact vault_uid
    - name: Store uid of user Vault
      ansible.builtin.set_fact:
        vault_uid: "{{ vault_user.uid }}"  

    # Create Hashicorp Vault container
    - name: "Create Hashicorp Vault container with id {{ image_id }}..."
      containers.podman.podman_container:
        name: vault
        image: "{{ image_id }}"
        cap_add: IPC_LOCK
        security_opt: label=disable
        privileged: true
        user: "{{ vault_uid }}"
        command: vault server -config=/vault/config/vault.hcl
        ports:
          - 8200:8200
        volumes:
          - /data/vault/config/:/vault/config:Z
          - /data/vault/file/:/vault/file:Z
          - /data/vault/logs/:/vault/logs:Z
        restart_policy: always
        env:
          SKIP_CHOWN: true
          SKIP_SETCAP: true

    # Wait for Hashicorp Vault to start
    - name: Wait for Hashicorp Vault container to start
      ansible.builtin.wait_for:
        host: localhost
        port: 8200
        delay: 5
        timeout: 60

    ##################################
    # Configure autostart container  #
    ##################################

    # Create folder for systemd unit file
    - name: Create folder for systemd unit file
      ansible.builtin.file:
        path: /home/vault/.config/systemd/user
        state: directory
        owner: vault
        mode: 0766

    # Stop Vault container
    - name: Stop Vault container
      containers.podman.podman_container:
        name: container
        image: "{{ image_id }}"
        state: absent
    
    # Prune containers
    - name: Prune everything
      containers.podman.podman_prune:
        volume: true

    # Auto-start Vault container on system boot
    - name: Generate systemd unit file for Vault container
      containers.podman.podman_generate_systemd:
        name: vault
        new: true
        no_header: true
        dest: /home/vault/.config/systemd/user

    # Set systemd unit file permissions
    - name: Set systemd unit file permissions
      ansible.builtin.file:
        path: /home/vault/.config/systemd/user/container-vault.service
        owner: vault
        mode: 0644

    # Reload systemd with shell. Use user vault
    - name: Reload systemd with shell. Use user vault
      ansible.builtin.shell: "systemctl --user daemon-reload"
      become: true
      become_user: vault
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ vault_uid }}"
    
    # Enable systemd service for Vault container
    #- name: Enable systemd service for Vault container
    #  ansible.builtin.shell: "systemctl --user enable --now container-vault.service"
    #  become: true
    #  become_user: vault
    #  environment:
    #    XDG_RUNTIME_DIR: "/run/user/{{ vault_uid }}"

#########################################################
## Installation on kubernetes                         ##
#########################################################

- name: Install Vault on Kubernetes
  when: platform == "kubernetes"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install Hashicorp Vault on kubernetes"
  
    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Installation on host                                ##
#########################################################

- name: Install Vault on host
  when: platform == "host"
  block:

    # Debug message
    - name: Debug message
      ansible.builtin.debug:
        msg: "Install Hashicorp Vault on host"
  
    # Show information message
    - name: This part is not (yet) implemented.
      ansible.builtin.debug:
        msg: "This part is not (yet) implemented."

    # Stop playbook
    - name: Stop playbook
      ansible.builtin.meta: end_play

#########################################################
## Configuration                                       ##
#########################################################

# Register vault_address
# TODO
- name: Register vault_address
  ansible.builtin.set_fact:
    vault_address: "http://localhost:8200"

# Configure Hashicorp Vault
- name: Configure
  ansible.builtin.include_tasks: configure.yml

#########################################################
## Post-install                                        ##
#########################################################

# Unset variables
- name: Unset variables
  ansible.builtin.set_fact:
    repository_tag:
    data_dir:
