---

#########################################################
## Pre-installation platform check                     ##
#########################################################

# Override platform check if platform variable is defined.
- name: Override platform check if platform variable is defined.
  set_fact:
    platform_check: false
  when: platform is defined

# Check if Podman is installed
- name: Check if Podman is installed
  command: podman --version
  register: podman_version_output
  ignore_errors: true
  when: platform_check is not defined

# Set platform if Podman is detected
- name: Set platform if Podman is detected
  set_fact:
    platform: "podman"
  when: 
    - platform_check is not defined
    - '"podman" in podman_version_output.stdout'

# Check if kubernetes is installed
# TODO

# If no podman or kubernetes is detected, use install on host
# TODO

#########################################################
## Pre-installation uninstall                          ##
#########################################################

# Run uninstall if uninstall is set
- name: Run uninstall playbook if set
  include_tasks: uninstall.yml
  ignore_errors: true
  when: uninstall == true

#########################################################
## Pre-installation folders                            ##
#########################################################

# Create Hashicorp Vault config folder
- name: Create Hashicorp Vault config folder
  file:
    path: /data/vault/config
    state: directory

# Create Hashicorp Vault storage folder
- name: Create Hashicorp Vault storage folder
  file:
    path: /data/vault/file
    state: directory

# Create Hashicorp Vault logs folder
- name: Create Hashicorp Vault logs folder
  file:
    path: /data/vault/logs
    state: directory

#########################################################
## Pre-installation user/group                         ##
#########################################################

# Create Hashicorp Vault user group
- name: Create Hashicorp Vault user group
  group: 
    name: "vault"
  become: true

# Create Hashicorp Vault user
- name: Create Hashicorp Vault user
  user:
    name: "vault"
    group: "vault"
    system: yes
    shell: "/sbin/nologin"
    comment: "Vault nologin User"
    createhome: "no"
    state: present

#########################################################
## Installation via podman                             ##
#########################################################

- block:

  # Create Hashicorp Vault configuration
  - name: Create Hashicorp Vault configuration
    template:
      src: ./templates/vault.podman_config.hcl.j2
      dest: /data/vault/config/vault.hcl

  # Create Hashicorp Vault pod
  - name: Create Hashicorp Vault pod
    containers.podman.podman_container:
      name: vault
      image: "{{ repository_url }}:latest"
      cap_add: IPC_LOCK
      security_opt: label=disable
      privileged: yes
      command: vault server -config=/vault/config/vault.hcl
      ports:
        - 8200:8200
      volumes:
        - /data/vault/config/:/vault/config:Z
        - /data/vault/file/:/vault/file:Z
        - /data/vault/logs/:/vault/logs:Z
      restart_policy: always

  # Wait for Hashicorp Vault to start
  - name: Wait for Hashicorp Vault pod to start
    wait_for:
      host: localhost
      port: 8200
      delay: 5
      timeout: 60

  # Auto-start Vault pod on boot
  - name: Generate systemd unit file for Vault pod
    containers.podman.podman_generate_systemd:
      name: vault
      new: true
      no_header: true
      dest: /etc/systemd/system
  
  
  when: platform == "podman"

#########################################################
## Installation via kubernetes                         ##
#########################################################

- block:

  # Debug message
  - name: Debug message
    debug:
      msg: "Install Hashicorp Vault via kubernetes"
  
  # Show information message
  - name: This part is not (yet) implemented.
    debug:
      msg: "This part is not (yet) implemented."

  # Stop playbook
  - name: Stop playbook
    meta: end_play

  when: platform == "kubernetes"

#########################################################
## Installation on host                                ##
#########################################################

- block:

  # Debug message
  - name: Debug message
    debug:
      msg: "Install Hashicorp Vault on host"
  
  # Show information message
  - name: This part is not (yet) implemented.
    debug:
      msg: "This part is not (yet) implemented."

  # Stop playbook
  - name: Stop playbook
    meta: end_play

  when: platform == "host"

#########################################################
## Configuration                                       ##
#########################################################

# Register vault_address
# TODO
- name: Register vault_address
  set_fact:
    vault_address: "http://localhost:8200"

# register vault_name
- name: Register vault_name
  set_fact:
    vault_name: "{{ admin_hostname | replace('.','-')}}"

# Configure Hashicorp Vault
- name: Configure
  include_tasks: configure.yml
    
# Create secret engine
- name: Create secret engine
  include_tasks: secret_engine.yml
  vars:
    action: create_secret_engine
    vault_description: "Secrets for {{ admin_hostname }}"
