--- 

- name: Set wait
  set_fact:
    wait: false
  when: wait is not defined

- name: Verify variable input
  assert:
    that:
      - action is defined and action in actions
    fail_msg: "Please provide 'action' {{ actions }}"
    quiet: true

- name: Install Hashicorp Vault in Podman
  include_tasks: install.yml
  when: action == "install"

- name: Uninstall Hashicorp Vault in Podman
  include_tasks: uninstall.yml
  when: action == "uninstall"

- name: Configure Hashicorp Vault
  include_tasks: configure.yml
  when: action == "configure"

- name: Unseal Vault
  include_tasks: unseal.yml
  when: action == "unseal"

  # secret_engine
- name: Get secret engine for Hashicorp Vault
  include_tasks: secret_engine.yml
  when: action == "get_secret_engine"

- name: Create secret engine for Hashicorp Vault
  include_tasks: secret_engine.yml
  when: action == "create_secret_engine"

- name: Destroy secret engine for Hashicorp Vault
  include_tasks: secret_engine.yml
  when: action == "destroy_secret_engine"

  # secrets
- name: Get secret key/value for Vault
  include_tasks: secrets.yml
  when: action == "get_secret"

- name: Create secret key/value for Vault
  include_tasks: secrets.yml
  when: action == "create_secret"

- name: Destroy secret key/value for Vault
  include_tasks: secrets.yml
  when: action == "destroy_secret"

  # policies
- name: Get policy for Vault
  include_tasks: policies.yml
  when: action == "get_policy"

- name: Create policy for Vault
  include_tasks: policies.yml
  when: action == "create_policy"

- name: Destroy policy for Vault
  include_tasks: policies.yml
  when: action == "destroy_policy"

  # approles
- name: Get AppRole for Vault
  include_tasks: approles.yml
  when: action == "get_approle"

- name: Create AppRole for Vault
  include_tasks: approles.yml
  when: action == "create_approle"

- name: Destroy AppRole for Vault
  include_tasks: approles.yml
  when: action == "destroy_approle"

