---

#########################################################
## Hashicorp Vault SSH Secret Engine module            ##
#########################################################

#########################################################
## Get SSH Secrets engine                              ##
#########################################################


#########################################################
## Create SSH Secrets engine                           ##
#########################################################

- name: Create Vault KV secret engine
  when: action == 'create_secret_engine'
  block:

  # Validate variables
    - name: Validate variables for Vault create_secret_engine action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop: 
        - vault_name
        - vault_description
   
    # Create Hashicorp secrets engine via api. Authenticate with vault_token.
    - name: Create Hashicorp secrets engine via api
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/mounts/{{ vault_name }}"
        validate_certs: false
        method: POST
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          type: ssh
          description: "{{ vault_description }}"




#########################################################
## Destroy KV Secrets engine                           ##
#########################################################

- name: Destroy Vault SSH secret engine
  when: action == 'destroy_secret_engine'
  block:

  # Validate local variables
    - name: Validate variables for Vault destroy_secret_engine action.
      ansible.builtin.assert:
        that: "{{ varitem }} is defined"
        fail_msg: "Required variable '{{ varitem }}' has not been provided."
        quiet: true
      loop_control:
        loop_var: varitem
      loop: 
        - vault_name

    # Destroy Hashicorp secrets engine via api. Authenticate with vault_token.
    - name: "Destroy Hashicorp secrets engine {{ vault_name }}"
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/sys/mounts/{{ vault_name }}"
        validate_certs: false
        method: DELETE
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"
