---

#########################################################
## Uninstall folders                                   ##
#########################################################

# Remove Vault config folder
- name: Remove Hashicorp Vault config folder
  ansible.builtin.file:
    path: /data/vault/config
    state: absent

# Remove Vault data folder
- name: Remove Hashicorp Vault storage folder
  ansible.builtin.file:
    path: /data/vault/file
    state: absent

# Remove Vault log folder
- name: Remove Hashicorp Vault log folder
  ansible.builtin.file:
    path: /data/vault/logs
    state: absent

#########################################################
## Uninstall via podman                                ##
#########################################################

- name: Uninstall via podman
  when: platform == "podman"
  block:
    # Remove Hashicorp Vault container
    - name: Remove Hashicorp Vault container
      containers.podman.podman_container:
        name: vault
        state: absent

#########################################################
## Uninstall users/groups                              ##
#########################################################

# Delete user Vault
- name: Delete user Vault
  ansible.builtin.user:
    name: vault
    state: absent
    force: true

# Delete user group vault
- name: Delete user group vault
  ansible.builtin.group: 
    name: "vault"
    state: absent
