---

#########################################################
## Uninstall configuration                             ##
#########################################################

# Remove Vault config folder
- name: Remove Hashicorp Vault config folder
  ansible.builtin.file:
    path: /data/vault/config
    state: absent

# Remove Vault data folder
- name: Remove Hashicorp Vault storage folder
  ansible.builtin.file:
    path: /data/vault/file
    state: absent

# Remove Vault log folder
- name: Remove Hashicorp Vault log folder
  ansible.builtin.file:
    path: /data/vault/logs
    state: absent

#########################################################
## Uninstall via podman                                ##
#########################################################

- name: Uninstall via podman
  when: platform == "podman"
  block:
  
    # Remove Hashicorp Vault pod
    - name: Remove Hashicorp Vault pod
      containers.podman.podman_container:
        name: vault
        state: absent
