---

#########################################################
## Installation                                        ##
#########################################################

# Install cockpit packages
- name: Install auto update package
  ansible.builtin.package:
    name:
      - dnf-automatic
    state: present

# Enable auto update service
# https://access.redhat.com/solutions/2823901
- name: Make sure a service unit is running
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: dnf-automatic-install.timer
