---

#########################################################
## Pre-installation                                    ##
#########################################################

#########################################################
## Network configuration                               ##
#########################################################

# Set hostname
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ admin_hostname }}"
  when: admin_hostname is defined

# Set timezone to Europe/Amsterdam
- name: Set timezone to Europe/Amsterdam
  community.general.timezone:
    name: Europe/Amsterdam

# Remove IPv6 from hosts file
- name: Remove IPv6 from hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^::1'
    state: absent

#########################################################
## User & groups configuration                         ##
#########################################################

# Make sure we have a 'wheel' group
- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

# Allow wheel group to sudo without password
- name: Allow wheel group to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# Check if admin_username is defined. Otherwise set value
- name: Check if admin_username is defined. Otherwise set default value.
  ansible.builtin.set_fact:
    admin_username: "admin"
    admin_usercomment: "Default admin user. Set with Managemant role."
  when: admin_username is not defined

# Check if admin_password is defined. Otherwise set value
- name: Check if admin_username is defined. Otherwise set value
  ansible.builtin.set_fact:
    admin_password: "P@ssw0rd!"
  when: admin_password is not defined

# Add user
- name: "Create user {{ admin_username }} for {{ admin_hostname }}"
  ansible.builtin.user:
    name: "{{ admin_username }}"
    comment: "{{ admin_usercomment }}"
    groups: wheel
    password: "{{ admin_password | password_hash('sha512', 'salt') }}"
    state: present

#########################################################
## SSH configuration                                   ##
#########################################################

# Generate SSH key
- name: Generate SSH key
  ansible.builtin.user:
    name: "{{ admin_username }}"
    generate_ssh_key: true
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: ""
    force: false
