---

- name: Set wait
  ansible.builtin.set_fact:
    wait: false
  when: wait is not defined

- name: Verify variable input
  ansible.builtin.assert:
    that:
      - action is defined and action in actions
    fail_msg: "Please provide 'action' {{ actions }}"
    quiet: true

- name: Configure base-server-config settings for lab playground
  ansible.builtin.include_tasks: configure_playground.yml
  when: action == "configure_playground"

- name: Configure Vault for base-server-config settings
  ansible.builtin.include_tasks: configure_vault.yml
  when: action == "configure_vault"
